### ISSUE TITLE
Action must fail on error

### ISSUE THREAD

**Issue by nazar-pc** [skymatic/code-sign-action#2]
I've got this error in logs, but the action itself didn't fail:
```
CertUtil: -importPFX command FAILED: 0x80070056 (WIN32: 86 ERROR_INVALID_PASSWORD)
CertUtil: The specified network password is not correct.
```

I think action should fail if it can't sign an executable.

**Comment by infeo** [comment]
Sorry for the long time to pick it up again. This should be fixed with version 2.0.0/3.0.0 respektively.
