### ISSUE TITLE
Node.js 12 is deprecated

### ISSUE THREAD

**Issue by cdgriffith** [skymatic/code-sign-action#5]
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: skymatic/code-sign-action@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

I think your latest version has been updated, but there is currently only the v1 branch, so may be as simple as new v2 branch? 

Thanks for this handy action!

**Comment by infeo** [comment]
Oi, just found this issue. Sorry for not replying. The action switched to node.js 16 with release [2.0.0](https://github.com/skymatic/code-sign-action/releases/tag/v2.0.0) and to node.js 20 with release [3.0.0](https://github.com/skymatic/code-sign-action/releases/tag/v3.0.0)
